version: '3.0'

services:

  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    ports:
      - "9000"
    depends_on:
      - "mariadb"
    volumes:
      - ${VOLUMES_PATH}/wordpress:/var/www/wordpress
    networks:
      - inception
    restart: on-failure
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - WP_DATABASE=${WP_DATABASE}
      - WP_TITLE=${WP_TITLE}
      - WP_ADMIN=${WP_ADMIN}
      - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_USER=${WP_USER}
      - WP_USER_PASSWORD=${WP_USER_PASSWORD}
      - WP_USER_EMAIL=${WP_USER_EMAIL}
      - DOMAIN_NAME=${DOMAIN_NAME}
 
  nginx:
    build: requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ${VOLUMES_PATH}/wordpress:/var/www/wordpress
    networks:
      - inception
    restart: on-failure

  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    ports:
      - "3306"
    volumes:
      - ${VOLUMES_PATH}/mariadb:/var/lib/mysql
    networks:
      - inception
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - WP_DATABASE=${WP_DATABASE}

networks:
  inception:

volumes:
  volume-mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${VOLUMES_PATH}/mariadb
  volume-wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${VOLUMES_PATH}/wordpress

